name: Daily Notion Changelog (JST)

on:
  schedule:
    - cron: '5 15 * * *'   # JST 00:05
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # ← トークンは OVERLEAF_SYNC_TOKEN を参照
      NOTION_TOKEN: ${{ secrets.OVERLEAF_SYNC_TOKEN }}
      # ← DB ID は従来どおり DOCS_DB_ID を参照（変えていなければこのまま）
      NOTION_DATABASE_ID: ${{ secrets.DOCS_DB_ID }}
      TZ: Asia/Tokyo
      TARGET_BRANCH: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run daily summary
        run: |
          python scripts/daily_changelog.py
